language: generic 
sudo: required
services:
    - docker

before-install:
    - docker build -t ayuraj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ayuraj/docker-react npm run test